import "./globals.css";
import { Lato } from "next/font/google";

import HomeContainer from "@/layouts/HomeContainer/HomeContainer";
import Footer from "@/layouts/Footer";
import NavigationBar from "@/layouts/NavigationBar/";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Top Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} tracking-wider h-screen flex flex-col`}
      >
        <HomeContainer>
          <NavigationBar />
          <main className="bg-slate-100 p-32 flex-1">{children}</main>
          <Footer />
        </HomeContainer>
      </body>
    </html>
  );
}
