import "./globals.css";
import { Lato } from "next/font/google";

import Footer from "@/layouts/Footer";
import NavigationBar from "@/layouts/NavigationBar/";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Top Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lato.className} tracking-wider`}>
        <NavigationBar />
        <main className="w-full h-screen bg-slate-100 p-32">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
